<?php
    $magazine = $this->displayMagazine();
    if (count($magazine) > 0) {
    ?>
    <div class="for-not-tablet enkiosque1"><img src="<?php echo $magazine['image']; ?>" alt="<?php echo $magazine['name']; ?>" /></div> 
    <div class="for-tablet enkiosque1"><img src="<?php echo $magazine['image']; ?>" alt="<?php echo $magazine['name']; ?>" /></div>
    <div class="for-desktop enkiosque2"><img src="<?php echo $this->getSkinUrl('images/enkiosque2.png'); ?>" alt="<?php echo $magazine['name']; ?>" /></div>
    
    <?php } ?>