<?php
    $banner = $this->displayBanner();
    // array(4) { 
    //  ["name"]=> string(14) "Nom de l'image" 
    //  ["image"]=> string(62) "http://burda.udhost.ovh/media/banner/image/t/e/test-600-200jpg" 
    //  ["alt"]=> string(14) "Alt de l'image" 
    //  ["link"]=> string(8) "mon lien" 
    //  } 
    if (count($banner) > 0) {
    ?>
    <div>
        <a href="<?php echo $banner['link']; ?>" title="<?php echo $banner['name']; ?>">
            <img src="<?php echo $banner['image']; ?>" name="<?php echo $banner['alt']; ?>">
        </a>
    </div>
    <?php } ?>